//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizoPlugin {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizoPlugin.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   切り取り(&amp;T);コピー(&amp;C);貼り付け(&amp;P);削除(&amp;D);テキストの色(&amp;L);フォント(&amp;F);色の選択(&amp;C);デフォルトの色(&amp;D);フォントサイズを大きく(&amp;L);フォントサイズを小さく(&amp;S);フォントを選択(&amp;C)...;デフォルトのフォント(&amp;D);検索(&amp;S);常に手前に表示(&amp;W) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string menu_ja {
            get {
                return ResourceManager.GetString("menu_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show folder &amp;memo;Show if exists;Show always;Stop;Memo;Focus on memo;Show on mouse hover over a tab with memo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_en {
            get {
                return ResourceManager.GetString("str_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダのメモを表示;メモがあれば表示;常に表示;停止;メモ;メモ欄にフォーカスを移す;メモがあるタブにマウスホバーで表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_ja {
            get {
                return ResourceManager.GetString("str_ja", resourceCulture);
            }
        }
    }
}
