//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.296
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizoPlugins {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizoPlugins.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap CopyButton_large {
            get {
                object obj = ResourceManager.GetObject("CopyButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CopyButton_small {
            get {
                object obj = ResourceManager.GetObject("CopyButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CopyToButton_large {
            get {
                object obj = ResourceManager.GetObject("CopyToButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CopyToButton_small {
            get {
                object obj = ResourceManager.GetObject("CopyToButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CutButton_large {
            get {
                object obj = ResourceManager.GetObject("CutButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CutButton_small {
            get {
                object obj = ResourceManager.GetObject("CutButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Add Cut button to ButtonBar.;Add Copy button to ButtonBar.;Add Paste button to ButtonBar.;Add Delete button to ButtonBar.;Add button to open copy-to-folder dialog.;Add button to open move-to-folder dialog.;Add Undo button to ButtonBar.;Add button to move selected files and folders to parent folder. Copies with Ctrl key down.;Add Properties button to ButtonBar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string dcpt {
            get {
                return ResourceManager.GetString("dcpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを切り取るボタンをボタンバーに追加します。;ファイルをコピーするボタンをボタンバーに追加します。;ファイル貼り付けるボタンをボタンバーに追加します。;ファイルを削除するボタンをボタンバーに追加します。;「フォルダへコピー」ダイアログを表示するボタンをボタンバーに追加します。;「フォルダへ移動」ダイアログを表示するボタンをボタンバーに追加します。;ファイル操作を元に戻すボタンをボタンバーに追加します。;選択ファイルやフォルダを一階層上のフォルダに移動するボタンをボタンバーに追加します。ボタンをCtrlキーと同時押しで移動でなくコピーします。
        ///キーボードショートカットも提供します。;選択ファイルや現在のフォルダのプロパティを表示するボタンをボタンバーに追加します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string dcpt_ja {
            get {
                return ResourceManager.GetString("dcpt_ja", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DeleteButton_large {
            get {
                object obj = ResourceManager.GetObject("DeleteButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteButton_small {
            get {
                object obj = ResourceManager.GetObject("DeleteButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoveToButton_large {
            get {
                object obj = ResourceManager.GetObject("MoveToButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoveToButton_small {
            get {
                object obj = ResourceManager.GetObject("MoveToButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PasteButton_large {
            get {
                object obj = ResourceManager.GetObject("PasteButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PasteButton_small {
            get {
                object obj = ResourceManager.GetObject("PasteButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PropertiesButton_large {
            get {
                object obj = ResourceManager.GetObject("PropertiesButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PropertiesButton_small {
            get {
                object obj = ResourceManager.GetObject("PropertiesButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedoButton_large {
            get {
                object obj = ResourceManager.GetObject("RedoButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedoButton_small {
            get {
                object obj = ResourceManager.GetObject("RedoButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SelectFileByExtension_large {
            get {
                object obj = ResourceManager.GetObject("SelectFileByExtension_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SendToParentButton_large {
            get {
                object obj = ResourceManager.GetObject("SendToParentButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SendToParentButton_small {
            get {
                object obj = ResourceManager.GetObject("SendToParentButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cut;Copy;Paste;Delete;Copy To Folder;Move To Folder;Undo;Move To Parent;Properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str {
            get {
                return ResourceManager.GetString("str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り取り;コピー;貼り付け;削除;フォルダへコピー;フォルダへ移動;元に戻す;一階層上へ移動;プロパティ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_ja {
            get {
                return ResourceManager.GetString("str_ja", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UndoButton_large {
            get {
                object obj = ResourceManager.GetObject("UndoButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UndoButton_small {
            get {
                object obj = ResourceManager.GetObject("UndoButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
