//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.261
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizoPlugins {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizoPlugins.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Segoe UI;9 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultFont {
            get {
                return ResourceManager.GetString("DefaultFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Meiryo UI;9 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultFont_ja {
            get {
                return ResourceManager.GetString("DefaultFont_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window manager option;Enlarge window;Shrink window;Widen window;Narrow widnow;Heighten window;Lower window;Restore initial size;Move window left;Move window right;Move window up;Move window down;Maximize window;Minimize window;Restore window;Tile explorer windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KeyboardShortcutNames {
            get {
                return ResourceManager.GetString("KeyboardShortcutNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウマネージャ オプション;ウィンドウ拡大;ウィンドウ縮小;幅拡大;幅縮小;高さ拡大;高さ縮小;元のサイズに戻す;ウィンドウを左へ;ウィンドウを右へ;ウィンドウを上へ;ウィンドウを下へ;最大化;最小化;元に戻す;エクスプローラを並べる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KeyboardShortcutNames_ja {
            get {
                return ResourceManager.GetString("KeyboardShortcutNames_ja", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap QTWindowManager_large {
            get {
                object obj = ResourceManager.GetObject("QTWindowManager_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QTWindowManager_small {
            get {
                object obj = ResourceManager.GetObject("QTWindowManager_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Window manager;Manage window size and position. ;Restore tiled explorer windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResStrs {
            get {
                return ResourceManager.GetString("ResStrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウマネージャ;起動時のウィンドウのサイズや場所を設定したり、移動したりできます。ショートカットも提供します。;並べたエクスプローラを戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResStrs_ja {
            get {
                return ResourceManager.GetString("ResStrs_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResStrs_Options {
            get {
                return ResourceManager.GetString("ResStrs_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時のサイズ;起動時の位置;サイズを復元;位置を復元;リサイズするときウィンドウの中心位置を保存;リサイズ/移動時のピクセル;プリセット;保存;削除;OK;キャンセル;現在の位置取得;現在のサイズ取得;起動時プリセット;取得;適用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResStrs_Options_ja {
            get {
                return ResourceManager.GetString("ResStrs_Options_ja", resourceCulture);
            }
        }
    }
}
