//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizoPlugins {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizoPlugins.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Current drive info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string currentDriveInfo {
            get {
                return ResourceManager.GetString("currentDriveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カレントドライブ情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string currentDriveInfo_ja {
            get {
                return ResourceManager.GetString("currentDriveInfo_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current folder info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string currentFolderInfo {
            get {
                return ResourceManager.GetString("currentFolderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カレントフォルダ情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string currentFolderInfo_ja {
            get {
                return ResourceManager.GetString("currentFolderInfo_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find empty folders and 0 byte files.;Provides shortcut keys to select / filter by seleted file extension.
        ///(To filter files, Search box is required in the ButtonBar.) ;Indicates file/folder informations such as folder size, modified date... in status bar. (Windows7);Enable to edit attributes of selected files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string dcpt {
            get {
                return ResourceManager.GetString("dcpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のフォルダで空のフォルダやサイズが0バイトのファイルを見つけます。;選択中のファイルの拡張子と同じものを選択したり、フィルタするキーボードショートカットを提供します。
        ///(フィルタするためには検索ボックスが追加されていることが必要です。);選択されたフォルダのサイズなどの情報をステータスバーに表示します。
        ///フォルダのサイズ、更新/作成日時などから選べます。(Windows7);選択ファイルの属性を編集します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string dcpt_ja {
            get {
                return ResourceManager.GetString("dcpt_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap EditAttributes_large {
            get {
                object obj = ResourceManager.GetObject("EditAttributes_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap EditAttributes_small {
            get {
                object obj = ResourceManager.GetObject("EditAttributes_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Enable in network folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enableForNetwork {
            get {
                return ResourceManager.GetString("enableForNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ネットワークフォルダでも有効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enableForNetwork_ja {
            get {
                return ResourceManager.GetString("enableForNetwork_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retrieve folder size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string foldersize {
            get {
                return ResourceManager.GetString("foldersize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダーのサイズを取得する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string foldersize_ja {
            get {
                return ResourceManager.GetString("foldersize_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select empty files and folders.;Select files by extension;Filter files by extension;Stop getting size of selection;Toggle &apos;system&apos; attribute;Set &apos;system&apos; attribute;Remove &apos;system&apos; attribute;Toggle &apos;read-only&apos; attribute;Set &apos;read-only&apos; attribute;Remove &apos;read-only&apos; attribute;Toggle &apos;hidden&apos; attribute;Set &apos;hidden&apos; attribute;Remove &apos;hidden&apos; attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string keys {
            get {
                return ResourceManager.GetString("keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空ファイル/フォルダを選択します。;同じ拡張子のファイルを選択;同じ拡張子でフィルターする;選択ファイルサイズの計算を中断する;システム属性を切り替える;システム属性をつける;システム属性をはずす;読取り専用属性を切り替える;読取り専用属性をつける;読取り専用属性をはずす;隠し属性を切り替える;隠し属性をつける;隠し属性をはずす に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string keys_ja {
            get {
                return ResourceManager.GetString("keys_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select empty;Select by extension;Selection Info To StatusBar;Edit attributes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空ファイル選択ボタン;拡張子で選択;ステータスバーに選択ファイルの情報を;ファイル属性編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string name_ja {
            get {
                return ResourceManager.GetString("name_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SelectEmptyButton_large {
            get {
                object obj = ResourceManager.GetObject("SelectEmptyButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SelectEmptyButton_small {
            get {
                object obj = ResourceManager.GetObject("SelectEmptyButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SelectFileByExtension_large {
            get {
                object obj = ResourceManager.GetObject("SelectFileByExtension_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SelectFileByExtension_small {
            get {
                object obj = ResourceManager.GetObject("SelectFileByExtension_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SelectionInfoToStatusBar_large {
            get {
                object obj = ResourceManager.GetObject("SelectionInfoToStatusBar_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SelectionInfoToStatusBar_small {
            get {
                object obj = ResourceManager.GetObject("SelectionInfoToStatusBar_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///    folder; file; byte;Getting selection size...;Failed.;Aborted.;Free Space: ;Total Size: ; item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string selSize {
            get {
                return ResourceManager.GetString("selSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///    個のフォルダ; 個のファイル; バイト;サイズ取得中...;失敗;中断されました;空き領域: ;合計サイズ: ; 個の項目 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string selSize_ja {
            get {
                return ResourceManager.GetString("selSize_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Size in bytes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string sizeInBytes {
            get {
                return ResourceManager.GetString("sizeInBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バイト換算値も表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string sizeInBytes_ja {
            get {
                return ResourceManager.GetString("sizeInBytes_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select empty files and folders\nin this folder.;;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tooltip {
            get {
                return ResourceManager.GetString("tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のフォルダで空ファイル/フォルダを選択します。;;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tooltip_ja {
            get {
                return ResourceManager.GetString("tooltip_ja", resourceCulture);
            }
        }
    }
}
