//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.239
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sorter {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sorter.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Segoe UI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultFont_en {
            get {
                return ResourceManager.GetString("DefaultFont_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Meiryo UI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultFont_ja {
            get {
                return ResourceManager.GetString("DefaultFont_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add keyboard shortcuts to sort view and toolbar button. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string description_en {
            get {
                return ResourceManager.GetString("description_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルリストをソートするキーボードショートカットや、ツールバーボタンを提供します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string description_ja {
            get {
                return ResourceManager.GetString("description_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort by Name;Sort by Date Modified;Sort by Date Created;Sort by Item Type;Sort by Size;Sort by File Attributes;Sort by Keywords;Sort by Item Date;Sort by Author;Sort by Comment;Sort by File Description;Sort by Rating;Sort by Subject;Sort by Title;Sort by Artist;Sort by Album Artist;Sort by Album Title;Sort by Composer;Sort by Genre;Sort by Track Number;Sort by Duration;Sort by Year;Sort by Dimensions;Reverse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string keyShortcutNames_en {
            get {
                return ResourceManager.GetString("keyShortcutNames_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前でソート;更新日時でソート;作成日時でソート;種類でソート;サイズでソート;属性でソート;タグでソート;日付でソート;作成者でソート;コメントでソート;ファイルの説明でソート;評価でソート;件名でソート;タイトルでソート;アーティストでソート;アルバムのアーティストでソート;アルバムでソート;作曲者でソート;ジャンルでソート;トラック番号でソート;長さでソート;年でソート;大きさでソート;リバース に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string keyShortcutNames_ja {
            get {
                return ResourceManager.GetString("keyShortcutNames_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File View Sorter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string name_en {
            get {
                return ResourceManager.GetString("name_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   並び替えツール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string name_ja {
            get {
                return ResourceManager.GetString("name_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select items to display in the drop down menu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string settingForm_en {
            get {
                return ResourceManager.GetString("settingForm_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メニューに表示するアイテムを選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string settingForm_ja {
            get {
                return ResourceManager.GetString("settingForm_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name;Date Modified;Date Created;Item Type;Size;File Attributes;Keywords;Item Date;Author;Comment;File Description;Rating;Subject;Title;Artist;Album Artist;Album Title;Composer;Genre;Track Number;Duration;Year;Dimensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string sortColumnNames_en {
            get {
                return ResourceManager.GetString("sortColumnNames_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前;更新日時;作成日時;種類;サイズ;属性;タグ;日付;作成者;コメント;ファイルの説明;評価;件名;タイトル;アーティスト;アルバムのアーティスト;アルバム;作曲者;ジャンル;トラック番号;長さ;年;大きさ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string sortColumnNames_ja {
            get {
                return ResourceManager.GetString("sortColumnNames_ja", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Sorter_large {
            get {
                object obj = ResourceManager.GetObject("Sorter_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sorter_small {
            get {
                object obj = ResourceManager.GetObject("Sorter_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
