//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizoPlugin {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizoPlugin.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Abort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string abort {
            get {
                return ResourceManager.GetString("abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string abort_ja {
            get {
                return ResourceManager.GetString("abort_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CreateConsecutiveFile_large {
            get {
                object obj = ResourceManager.GetObject("CreateConsecutiveFile_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CreateConsecutiveFile_small {
            get {
                object obj = ResourceManager.GetObject("CreateConsecutiveFile_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CreateFolderButton_large {
            get {
                object obj = ResourceManager.GetObject("CreateFolderButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CreateFolderButton_small {
            get {
                object obj = ResourceManager.GetObject("CreateFolderButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CreateTextButton_large {
            get {
                object obj = ResourceManager.GetObject("CreateTextButton_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CreateTextButton_small {
            get {
                object obj = ResourceManager.GetObject("CreateTextButton_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ベース名;開始値;終了値;拡張子;桁を0で揃える;大量のとき警告;設定を保存;キャンセル;新しいアイテム ( %n% );作成したらすぐ閉じる;閉じるときに設定を保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string dialog_ja {
            get {
                return ResourceManager.GetString("dialog_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   These files/directories already exist.
        ///
        ///;Failed to create these files/directories.
        ///
        ///;You are creating {0} items.
        ///Do you really want to create so many?;Current folder not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下のファイル/フォルダは既に存在します。
        ///
        ///;以下のファイル/フォルダの作成に失敗しました。
        ///
        ///;{0} 個のアイテムを作成しようとしています。
        ///よろしいですか?;カレントフォルダが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Messages_ja {
            get {
                return ResourceManager.GetString("Messages_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいフォルダー;新しいテキストファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Name_ja {
            get {
                return ResourceManager.GetString("Name_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap text {
            get {
                object obj = ResourceManager.GetObject("text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   %n% is a placeholder for number.
        ///If %n% is not contained, numbers are added at the end of file name.;Create folders;Create files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tooltips {
            get {
                return ResourceManager.GetString("Tooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %n% は番号のプレースホルダです。
        ///%n% が含まれないときは末尾に番号が追加されます。;フォルダを作成;ファイルを作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tooltips_ja {
            get {
                return ResourceManager.GetString("Tooltips_ja", resourceCulture);
            }
        }
    }
}
